version: '3.4'

services:
  denoadaptorcase2:
    image: denoAdaptorCase
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
    
      - GOOGLE_SHEET_API_URL=https://sheets.googleapis.com/v4/spreadsheets
      - SPREADSHEET_ID=1frVzuJCImzpP-zEhSrzuQGV0rUp3mFxV5OfG0z1UZYg
      - API_KEY=AIzaSyBler_9a4lG0EQojqwWvBS5OtZHW_19kd4
      - SHEET_NAME=Dataset